"""empty message

Revision ID: 69ea59ec0840
Revises: 9af01e23f433
Create Date: 2020-08-03 02:10:11.864851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ea59ec0840'
down_revision = '9af01e23f433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False,autoincrement=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.alter_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True, default=True))
    op.alter_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True, default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'id')
    # ### end Alembic commands ###
